#!/bin/bash

# Programs
# Takuya's set-up
PYTHON=/usr/bin/python3.8

# Scripts
gen_filelist=./tools/gen_filelist.py
list2json=./tools/list2json_librispeech.py
mixspec=./tools/gen_mixspec_2spkr.py

# Directories
# Takuya's set-up
srcdir=/mnt/f/Work/JelinekWorkshop2020/data/train/wav_newseg  # Generated by preprocess.sh.
tgtroot=/mnt/f/Work/JelinekWorkshop2020/data/LibriCSS-train


# Hyper-parameters
ncopies=1
single_spkr=0.08


# cfgfile=./configs/2mixReverbNoiseLibriMix.json

# List the source files. 
trainlist=$tgtroot/train.list
# $PYTHON $gen_filelist --srcdir $srcdir --outlist $trainlist

# Create a JSON file for the source data set. 
trainjson=$tgtroot/train.json
$PYTHON $list2json --input_list $trainlist --output_file $trainjson

# Generate mixture specs. 
tgtdir=$tgtroot/wav
specjson=$tgtroot/mixspec.json
$PYTHON $mixspec --inputfile $trainjson --outputfile $specjson --ncopies $ncopies --single_speaker_percentage $single_spkr --targetdir $tgtdir

# Generate mixed audio files. 
